# Spicebird User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while Spicebird is running,
 * the changes will be overwritten when Spicebird exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

// Applet 0: Folder view applet
user_pref("collab.home.applets.0.column", 1);
user_pref("collab.home.applets.0.type", "mailnews-folderview-applet");
user_pref("collab.home.applets.0.weight", 0);
user_pref("collab.home.applets.0.mailnum", 5);
user_pref("collab.home.applets.0.unread", true);

// Applet 1: Clocks with local time and Los Angeles time
user_pref("collab.home.applets.1.column", 2);
user_pref("collab.home.applets.1.timezones", "--default--,America/Los_Angeles");
user_pref("collab.home.applets.1.type", "collab-datetime-applet");
user_pref("collab.home.applets.1.weight", 0);

// Applet 2: RSS Feed - Spicebird blog
user_pref("collab.home.applets.2.column", 3);
user_pref("collab.home.applets.2.numitems", 6);
user_pref("collab.home.applets.2.type", "mailnews-rssfeed-applet");
user_pref("collab.home.applets.2.url", "http://www.spicebird.com/blog/feed");
user_pref("collab.home.applets.2.weight", 0);

// Applet 4: Agenda on all calendars 
user_pref("collab.home.applets.4.column", 2);
user_pref("collab.home.applets.4.type", "calendar-agenda-applet");
user_pref("collab.home.applets.4.weight", 1);

// Applet 5: Google applet - Google maps
user_pref("collab.home.applets.5.column", 3);
user_pref("collab.home.applets.5.type", "collab-google-applet");
user_pref("collab.home.applets.5.url", "http://www.google.com/ig/modules/wikipedia.xml");
user_pref("collab.home.applets.5.weight", 1);

// Default statuses for Instant Messaging (Shown in recent statuses)
user_pref("collab.chat.statuses.0.message", "Spicebird!");
user_pref("collab.chat.statuses.0.status", "available");
user_pref("collab.chat.statuses.1.message", "Spicebird!");
user_pref("collab.chat.statuses.1.status", "away");
user_pref("collab.chat.statuses.2.message", "Spicebird!");
user_pref("collab.chat.statuses.2.status", "busy");
